variable "ENGINE" {}
variable "NODE_TYPE" {}
variable "NUM_CACHE_NODES" {}
variable "ENGINE_VERSION" {}
variable "PORT" {}
variable "COMPONENT" {}
variable "ENV" {}
variable "CIDR_BLOCK" {}
variable "VPC_ID" {}
variable "SUBNET_IDS" {}
variable "FAMILY" {}
